### ISSUE TITLE
NullReferenceException when transaction is null

### ISSUE THREAD

**Issue by cirrusone** [DapperLib/Dapper#1548]
The following code works fine:

```
sqlQuery = $"select [Image64] from [{_databaseOld}].[dbo].[Historic] where [Image64] is not null";
List<string> images = connection.Query<string>(sqlQuery, null).ToList();
```

Both the following fail and raise and error which seems to indicate that there is a problem with `transaction = null`:

```
sqlQuery = $"select [Image64] from [{_databaseOld}].[dbo].[Historic] where [Image64] is not null";
List<string> images = connection.Query<string>(sqlQuery, null , null, 600).ToList();
```

```
sqlQuery = $"select [Image64] from [{_databaseOld}].[dbo].[Historic] where [Image64] is not null";
List<string> images = connection.Query<string>(sqlQuery, null , null).ToList();
```

Error:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Dapper
  StackTrace:
   at Dapper.SqlMapper.<MultiMapImpl>d__157`1.MoveNext() in /_/Dapper/SqlMapper.cs:line 1472
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[TReturn](IDbConnection cnn, String sql, Type[] types, Func`2 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1394
   at ...Jobs.MigrateDatabase.DoMigration() in ...\Jobs\MigrateDatabase.cs:line 656
```

Project Details:

SQL data type: [Image64] [nvarchar](max) NULL

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.35" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Filters.Expressions" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
  </ItemGroup>

</Project>
```

**Comment by bgrainger** [comment]
The call stack indicates that you're calling the overload with this signature: `Dapper.SqlMapper.Query[TReturn](IDbConnection cnn, String sql, Type[] types, Func`2 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType)` that's defined here: https://github.com/StackExchange/Dapper/blob/2.0.35/Dapper/SqlMapper.cs#L1390

Thus, your code is passing `null` for `sql` and `types`, not `transaction`. There may be some argument validation missing in Dapper, but calling the wrong overload appears to be the root of your crash. Try using named parameters to ensure you're actually invoking the overload you want.

**Comment by NickCraver** [comment]
Bradley's right above - the signature isn't quite the one thought here. Closing out to cleanup.
