### ISSUE TITLE
Unable to mapped underscore column in dapper extension

### ISSUE THREAD

**Issue by waqasahmed0323** [DapperLib/Dapper#1825]
Hi, I have a user data model containing some underscore columns but I'm unable to insert, update and get records using the dapper extension library it is throwing reflection error below you can see:

at DapperExtensions.ReflectionHelper.GetParameter(Type entityType, ISqlGenerator sqlGenerator, String propertyName, Object value)
   at DapperExtensions.DapperImplementor.AddParameter[T](T entity, DynamicParameters parameters, IMemberMap prop, Boolean useColumnAlias)
   at DapperExtensions.DapperImplementor.GetDynamicParameters[T](T entity, IClassMapper classMap, IList`1 sequenceColumn, IList`1 foreignKeys, IList`1 ignoredColumns, Boolean useColumnAlias)
   at DapperExtensions.DapperImplementor.GetDynamicParameters[T](IClassMapper classMap, T entity, Boolean useColumnAlias)
   at DapperExtensions.DapperImplementor.InternalUpdate[T](IDbConnection connection, T entity, IClassMapper classMap, IPredicate predicate, IDbTransaction transaction, IList`1 cols, Nullable`1 commandTimeout, Boolean ignoreAllKeyProperties)
   at DapperExtensions.DapperAsyncImplementor.<InternalUpdateAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DapperExtensions.DapperAsyncImplementor.<InternalUpdateAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DapperExtensions.DapperAsyncImplementor.<UpdateAsync>d__3`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DapperExtensions.AsyncDatabase.<Update>d__8`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
---------------------------------------------------------------------------------------
User Data Model:
**public class Permission 
    {
        public Guid Id { get; set; }
        public string permission_code { get; set; }
        public string role_code { get; set; }
        public bool HasPermission { get; set; }
        public string PermissionStatus { get; set; }
        public string addl_data { get; set; }
    }**

**await db.Update<Permission>(roleView, null, true);**

Also, I set this property before and after the connection opened but this is not working throwing the above exception:

 **IDbConnection con = CreateConnection();
                if (con == null)
                    throw new ApplicationException("CreateConnection function did not return a valid connection"); 
                DefaultTypeMap.MatchNamesWithUnderscores = true;
                con.Open();**

**Comment by Bosegeek** [comment]
I assume you have 1:1 mapping with the column name in your data model with table columns. In case there is a discrepancy, either you can correct those or use System.ComponentModel.DataAnnotations.Schema.Column attribute for the properties in the data model. With the attribute added you might need to have some code added :

```
Dapper SqlMapper.TypeMapProvider = type =>
{
   var fallback = new DefaultTypeMap(type);
   return new CustomPropertyTypeMap(type, (t, column) =>
   {
       var property = t.GetProperties().FirstOrDefault(prop =› 
                     prop.GetCustomAttributes(typeof(ColumnAttribute), true)
                    .Cast<ColumnAttribute>()
                    .Any(attr => attr.Name == column));

        if (property == null)
        {
           property = fallback.GetMember(column)?.Property;
        }
        return property;
   });
};

**Comment by waqasahmed0323** [comment]
@Bosegeek Thanks for your reply, below is the data model I added in the Columns attribute as well, now I'm confused about adding this code, can you help me with the correct path of this piece of code?

`Dapper SqlMapper.TypeMapProvider = type =>
{
   var fallback = new DefaultTypeMap(type);
   return new CustomPropertyTypeMap(type, (t, column) =>
   {
       var property = t.GetProperties().FirstOrDefault(prop =› 
                     prop.GetCustomAttributes(typeof(ColumnAttribute), true)
                    .Cast<ColumnAttribute>()
                    .Any(attr => attr.Name == column));

        if (property == null)
        {
           property = fallback.GetMember(column)?.Property;
        }
        return property;
   });
};`

`public class Permission
{
        [Column("id")]
        public Guid Id { get; set; }
        [Column("permission_code")]
        public string permission_code { get; set; }
        [Column("role_code")]
        public string role_code { get; set; }
        [Column("haspermission")]
        public bool HasPermission { get; set; }
        [Column("permissionstatus")]
        public string PermissionStatus { get; set; }
        [Column("addl_data")]
        public string addl_data { get; set; }
}`

**Comment by waqasahmed0323** [comment]
@Bosegeek I added code in after & before open connection but sill getting same error:

` IDbConnection con = CreateConnection();
                if (con == null)
                    throw new ApplicationException("CreateConnection function did not return a valid connection");
                DefaultTypeMap.MatchNamesWithUnderscores = true;
                con.Open();
                SqlMapper.TypeMapProvider = type =>
                {
                    var fallback = new DefaultTypeMap(type);
                    return new CustomPropertyTypeMap(type, (t, column) =>
                    {
                        var property = t.GetProperties().FirstOrDefault(prop => 
                                     prop.GetCustomAttributes(typeof(System.ComponentModel.DataAnnotations.Schema.ColumnAttribute), true)
                                     .Cast<System.ComponentModel.DataAnnotations.Schema.ColumnAttribute>()
                                     .Any(attr => attr.Name == column));
                        if (property == null)
                        {
                            property = fallback.GetMember(column)?.Property;
                        }
                        return property;
                    });
                };`
