### ISSUE TITLE
Double  occurs "Error parsing column"

### ISSUE THREAD

**Issue by xinxianwu** [DapperLib/Dapper#1857]
We encountered a strange problem, sometimes "Error parsing column" exception occurs when executing the procedure.
When cs15 has the same value, sometimes it goes wrong, sometimes not, we can't figure out how to reproduce and fix it, hope someone can help us.

This is db schema :
[cs51] [decimal](9, 4) NULL

And this is declare type in c# :
public double Cs15 { get; set; }

`"Message": "Error parsing column 27 (cs15=0.0000 - Decimal)",
"StackTraceString": "   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706\n   at Deserializec777c448-0a1b-40d4-aa8d-397d18c753ac(IDataReader )\n   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1113\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\n   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734\n   at SunplusBettingLibrary.Repository.BaseRepository.StoredProcedureExecute[T](String spName, Object param)\n   at SunplusBettingLibrary.Repository.BetRepository.GetAnOddsExModel(GetOddsCriteriaModel getOddsCriteriaModel)\n   at SunplusBettingLibrary.Service.GetOddsService.GetAnOddsTableEx(GetOddsCriteriaModel getOddsCriteriaModel, Int32 custId, Boolean isDebugMode, Action`1 saveBetTypeMappingAction, Action letRobotUserSleepAction)\n   at SunplusBettingLibrary.BettingBase.GetAnOddsTableEx()\n   at OneLab.CommonCache.Standard.Base.GetCache(String inputkey)\n   at SunplusBettingLibrary.BettingBase.GetAnOddsEx(Int32 oddsId, Int32 betType, Int32 parentBetType, Boolean disabledCache, Int32 custId, Int32 sportType, Boolean debugMode, Int32 matchId, String marketId)\n   at SunplusBettingLibrary.UnderOver.GetBettingInfo(UnderOverTicket ticket, Boolean DisabledCache, DataRow RowData)"`

**Comment by RyoKakomi** [comment]
Could you try changing the property type from double to nullable decimal?

```C#
public decimal? Cs15 { get; set; }
```

**Comment by xinxianwu** [comment]
I tried it and got the following error

`System.Data.DataException: Error parsing column 27 (cs15=100.0000 - Decimal)
 ---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Double]'.
   at Deserializea3fa6e0b-daf6-4c19-b087-a859a982bef3(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserializea3fa6e0b-daf6-4c19-b087-a859a982bef3(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1113
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734`

**Comment by RyoKakomi** [comment]
@xinxianwu 

Thank you your response.

What database are you using?
(My code passed test.)

Entity
```C#
private class TestNullable
{
    public int Id { get; set; }
    public decimal? Cs15 { get; set; }
}
```

Query
```C#
conn.Execute("create table ttest ( id serial not null, cs15 decimal);");
conn.Execute("insert into ttest(cs15) values(:Cs15) ", new List<TestNullable>(Tests));
var result = conn.Query<TestNullable>("select * from ttest ");
```

**Comment by xinxianwu** [comment]
I using MSSQL.
Under normal circumstances, my program is also passed teste but it has a certain probability of exception, I can't find any rules, and I can't reproduce it.

Quoting my error log above : 
`System.Data.DataException: Error parsing column 27 (cs15=100.0000 - Decimal) ---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Nullable1[System.Double]'.
at Deserializea3fa6e0b-daf6-4c19-b087-a859a982bef3(IDataReader )
--- End of inner exception stack trace ---
at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in //Dapper/SqlMapper.cs:line 3706
at Deserializea3fa6e0b-daf6-4c19-b087-a859a982bef3(IDataReader )
at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in //Dapper/SqlMapper.cs:line 1113
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source) at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable1 commandTimeout, Nullable1 commandType) in /_/Dapper/SqlMapper.cs:line 734`

I think maybe dapper cache is confused, property type is `decimal?` but error message display `System.Decimal' to type 'System.Nullable1[System.Double]` , their type is not match.

**Comment by xinxianwu** [comment]
Here is the data model : 
```csharp
public class OddsDataModel
{
    public int MatchId { get; set; }
    public int MarketId { get; set; }
    public int OddsId { get; set; }
    public int BetType { get; set; }
    public int ParentBetType { get; set; }
    public DateTime EventDate { get; set; }
    public int SportType { get; set; }
    public string OddsStatus { get; set; }
    public int LeagueId { get; set; }
    public int HomeId { get; set; }
    public int AwayId { get; set; }
    public DateTime MarketEndTime { get; set; }
    public DateTime EndTime { get; set; }
    public string MatchCode { get; set; }
    public int ChildMatchType { get; set; }
    public int ParentId { get; set; }
    public double Odds1A { get; set; }
    public double Odds2A { get; set; }
    public double OddsAdj { get; set; }
    public double Cs00 { get; set; }
    public double Cs01 { get; set; }
    public double Cs02 { get; set; }
    public double Cs03 { get; set; }
    public decimal? Cs04 { get; set; }
    public double Cs05 { get; set; }
    public double Cs09 { get; set; }
    public double Cs10 { get; set; }
    public double Cs11 { get; set; }
    public double Cs12 { get; set; }
    public double Cs13 { get; set; }
    public double Cs14 { get; set; }
    public decimal? Cs15 { get; set; }
    public double Cs20 { get; set; }
    public double Cs21 { get; set; }
    public double Cs22 { get; set; }
    public double Cs23 { get; set; }
    public double Cs24 { get; set; }
    public double Cs25 { get; set; }
    public double Cs30 { get; set; }
    public double Cs31 { get; set; }
    public double Cs32 { get; set; }
    public double Cs33 { get; set; }
    public double Cs34 { get; set; }
    public double Cs35 { get; set; }
    public double Cs40 { get; set; }
    public double Cs41 { get; set; }
    public double Cs42 { get; set; }
    public double Cs43 { get; set; }
    public double Cs44 { get; set; }
    public double Cs45 { get; set; }
    public double Cs50 { get; set; }
    public double Cs51 { get; set; }
    public double Cs52 { get; set; }
    public double Cs53 { get; set; }
    public double Cs54 { get; set; }
    public double Cs90 { get; set; }
    public decimal? Cs99 { get; set; }
    public string CsStatus { get; set; }
    public double Hdp1 { get; set; }
    public double Hdp2 { get; set; }
    public double Com1 { get; set; }
    public double Com2 { get; set; }
    public double ComX { get; set; }
    public bool ComStatus { get; set; }
    public string EventStatus { get; set; }
    public string ExtraInfo { get; set; }
    public string ResourceId { get; set; }
    public bool IsToday { get; set; }
    // is live
    public bool LiveIndicator { get; set; }
    public int LiveHomeScore { get; set; }
    public int LiveAwayScore { get; set; }
    public bool IsNeutral { get; set; }
    public decimal MaxBet { get; set; }
    public decimal MaxPayout { get; set; }
    public DateTime KickOffTime { get; set; }
    public long DiffKickOffTime { get; set; }
    public int ErrorCode { get; set; }
    public int OddsTBType { get; set; }
    public int ExSpread { get; set; }
    public int DepSpread { get; set; }
    public int Sort { get; set; }
    public int SiteOddsGap1 { get; set; }
    public int SiteOddsGap2 { get; set; }
    public int SiteOddsGap3 { get; set; }
    public bool NewOfferSetup { get; set; }
    public bool SecAcceptFlag { get; set; }
    public int SecAccept { get; set; }
    public string DisplayMode { get; set; }
    public double MinOdds { get; set; }
    public double MaxOdds { get; set; }
    // OddsTBType = 0, bet type = 90 (number wheel)
    public int Ball1 { get; set; }
    // OddsTBType = 0, bet type = 90 (number wheel)
    public int Ball2 { get; set; }
    // OddsTBType = 3
    public decimal Price { get; set; }
    public int SelectionCounts { get; set; }
    public int SB_TradeStatusID { get; set; }
    // OddsTBType = 4
    public decimal OddsSpreadA { get; set; }
    public int EventStatusReason { get; set; }
    public bool CreditCP { get; set; }

}
```
And here is data schema
```sql
	matchid int NOT NULL,
	oddsid int NOT NULL,
	bettype smallint NULL,
	sporttype tinyint NOT NULL,
	oddsstatus nvarchar(50) NULL,
	liveindicator bit NULL,
	livehomescore int NULL,
	liveawayscore int NULL,
	leagueid int NOT NULL,
	homeid int NOT NULL,
	awayid int NOT NULL,
	ChildMatchType tinyint NOT NULL,
	ParentID int NOT NULL,
	odds1a float NULL,
	odds2a float NULL,
	odds1hkf float NULL,
	odds2hkf float NULL,
	oddsspreada float NULL,
	oddsspreadb float NULL,
	oddsspreadc float NULL,
	oddsspreadd float NULL,
	oddsspreade float NULL,
	oddsspreadf float NULL,
	hdp1 float NOT NULL,
	hdp2 float NOT NULL,
	maxbet float NOT NULL,
	cs99 float NOT NULL,
	cs15 decimal(9,4) NULL,
	cs25 decimal(9,4) NULL,
	cs35 decimal(9,4) NULL,
	cs45 decimal(9,4) NULL,
	cs32 float NULL,
	IsNeutral bit NOT NULL,
	eventstatus nvarchar(50) NULL,
	csstatus nvarchar(50) NULL,
	newoffersetup tinyint NOT NULL,
	SecAcceptFlag tinyint NOT NULL,
	SecAccept tinyint NOT NULL,
	OddsAdj float NULL,
	Resourceid varchar(20) NULL,
	MaxPayout float NOT NULL,
	DisplayMode tinyint NOT NULL,
	ParentBetType smallint NULL,
	kickofftime datetime NULL,
	DiffKickOffTime int NULL,
	ErrorCode tinyint NULL,
	OddsTBType tinyint NULL,
	minodds float NOT NULL,
	maxodds float NOT NULL,
	ExSpread smallint NOT NULL,
	IsToday bit NULL,
	DepSpread smallint NULL,
	Sort smallint NULL,
	SiteOddsGap1 smallint NOT NULL,
	SiteOddsGap2 smallint NOT NULL,
	SiteOddsGap3 smallint NOT NULL,
	EventStatusReason tinyint NOT NULL,
	CreditCP bit NOT NULL
```

**Comment by RyoKakomi** [comment]
@xinxianwu 
Thank you response.

I try MSSQL + your data model.
But, did not reproduce.

```C#
var list = new List<OddsDataModel>
{
    new() { MatchId = 0, Cs15 = (decimal)0.15, Cs99 = (decimal)99.99},
    new() { MatchId = 1, Cs15 = (decimal)0 , Cs99 = 0},
    new() { MatchId = 2, Cs15 = null },
    new() { MatchId = 2, Cs15 = (decimal)99999.9999, Cs99 = (decimal)0.15}
};

foreach (var model in list)
{
    conn.Execute($@"insert into odds(matchid, cs15, cs99) values(@{nameof(model.MatchId)}, @{nameof(model.Cs15)}, @{nameof(model.Cs99)})", model);
}

var result = conn.Query<OddsDataModel>("select * from odds",param:null, buffered:true );

Assert.Equal(result.Count(), list.Count);
```
Version infomation
* .NET 6
* Dapper 2.0.123



Could you try casting in a procedure.
