### ISSUE TITLE
 SqlMapper.AddTypeHandler Not being called. 

### ISSUE THREAD

**Issue by KarltonKemerait** [DapperLib/Dapper#1915]
VB.Net Windows desktop application, Dapper 2.0.123

Even though the typehandler is registered on app startup. Cx.Get(of T)(ID) - Fails saying unable to parse column 7 (the UDT Column). However, I CAN do an insert without any issues, even though SetValue is never called. Odd behavior.

'---- ERROR MSG ON READ---------
`System.Data.DataException: Error parsing column 7 (MailingAddress=Kemerait, Karlton  - String)
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'GlobalAddress, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'GlobalAddress, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Data.SqlClient.SqlConnection.ResolveTypeAssembly(AssemblyName asmRef, Boolean throwOnError)
   at Microsoft.Data.SqlClient.SqlConnection.<>c__DisplayClass197_0.<CheckGetExtendedUDTInfo>b__0(AssemblyName asmRef)
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at Microsoft.Data.SqlClient.SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValueInternal(Int32 i)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValue(Int32 i)
   at Microsoft.Data.SqlClient.SqlDataReader.get_Item(Int32 i)
   at Deserializeb514716b-d998-405c-9491-10e4b406c271(IDataReader)
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserializeb514716b-d998-405c-9491-10e4b406c271(IDataReader)
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Get[T](IDbConnection connection, Object id, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Elara.Dublin.Entity.BaseEntity.Retrieve[T](Int32 pID)`

'----TYPE HANDLER CLASS-------

`Imports Microsoft.Data.SqlClient

Public Class GlobalAddressTypeHandler

    Inherits SqlMapper.TypeHandler(Of GlobalAddress)

    Public Overrides Sub SetValue(ByVal parameter As IDbDataParameter, ByVal value As GlobalAddress)
        parameter.SourceColumn = "MailingAddress"
        parameter.Value = value.ToString

    End Sub

    Public Overrides Function Parse(ByVal value As Object) As GlobalAddress

        Dim Result As GlobalAddress

        Result = GlobalAddress.Parse(value.ToString)
        Return Result

    End Function

End Class`

'-------- UDT CLASS
`Option Explicit On
Option Strict On

Imports System.Data.SqlTypes
Imports Microsoft.SqlServer.Server
Imports System.Text
Imports System.IO

<Serializable(), SqlUserDefinedTypeAttribute(Format.UserDefined,
  IsByteOrdered:=True, IsFixedLength:=False, MaxByteSize:=255, ValidationMethodName:="ValidateAddress")>
Public Class GlobalAddress

    Implements INullable
    Implements IBinarySerialize

    Private MaxAddressSize As Integer = 192

    Public Property Address As String
    Public Property AutoFormat As Boolean
    Public Property Formatted As Boolean
    Public Property Longitude As Single
    Public Property Latitude As Single

    Private is_Null As Boolean

    Public Sub New()
        Me.Address = String.Empty
        Me.AutoFormat = True
        Me.Formatted = False
        Me.Longitude = 2.34
        Me.Latitude = 4.45
    End Sub

    Public ReadOnly Property IsNull() As Boolean _
       Implements INullable.IsNull
        Get
            Return (is_Null)
        End Get
    End Property

    Public Shared ReadOnly Property Null() As GlobalAddress
        Get
            Dim TmpAddress As New GlobalAddress
            TmpAddress.is_Null = True
            Return (TmpAddress)
        End Get
    End Property

    Public Overrides Function ToString() As String

        Dim Result As String = "NULL"
        Dim MyBuilder As StringBuilder = New StringBuilder

        If Me.IsNull Then
            Result = "NULL"
        Else

            If Me.Address = String.Empty Then
                Result = String.Empty
            Else

                With MyBuilder
                    .Append(Me.Address)
                    .Append("|")
                    .Append(Me.AutoFormat)
                    .Append("|")
                    .Append(Me.Formatted)
                    .Append("|")
                    .Append(Me.Longitude)
                    .Append("|")
                    .Append(Me.Latitude)

                End With

            End If

            Result = MyBuilder.ToString

        End If

        Return Result

    End Function

    <SqlMethod(OnNullCall:=False)>
    Public Shared Function Parse(ByVal s As SqlString) As GlobalAddress

        Dim TmpAddress As New GlobalAddress
        Dim AddressString() As String

        If s.IsNull Then
            Return Null
        End If

        If s = String.Empty Then
            TmpAddress.Address = String.Empty
            TmpAddress.AutoFormat = True
            TmpAddress.Formatted = False
        Else
            AddressString = s.Value.Split("|".ToCharArray())
            TmpAddress.Address = AddressString(0)
            TmpAddress.AutoFormat = CBool(AddressString(1))
            TmpAddress.Formatted = CBool(AddressString(2))
        End If

        Return TmpAddress

    End Function

    Private Function ValidateAddress() As Boolean

        Return True

    End Function

    Public Sub Read(r As BinaryReader) Implements IBinarySerialize.Read

        Dim AddressText As Char()
        Dim AddressTextLength As Integer

        AddressText = r.ReadChars(Me.MaxAddressSize)
        AddressTextLength = Array.IndexOf(AddressText, CChar(vbNullChar))

        If AddressTextLength > 0 Then

            Me.Address = New String(AddressText, 0, AddressTextLength)

            Me.AutoFormat = r.ReadBoolean
            Me.Formatted = r.ReadBoolean
            Me.Latitude = r.ReadSingle
            Me.Longitude = r.ReadSingle

        Else
            ' Do Not Process Anything
        End If

    End Sub

    Public Sub Write(w As BinaryWriter) Implements IBinarySerialize.Write

        Dim PaddedAddress As String

        PaddedAddress = Me.Address.PadRight(Me.MaxAddressSize, CChar(vbNullChar))

        For i As Integer = 0 To PaddedAddress.Length - 1
            w.Write(PaddedAddress(i))
        Next

        w.Write(Me.AutoFormat)
        w.Write(Me.Formatted)
        w.Write(Me.Latitude)
        w.Write(Me.Longitude)

    End Sub

End Class`

'----- SNIPPIT OF DAPPER SAVE/INSERT

`      Protected Function Save(Of T As Class)(ByVal pRecord As T) As Boolean

            Dim Result As Boolean = False

            Me.PreValidate()
            If Me.Log.HasEntries Then
                Result = False
            Else

                Try

                    Using Cx = DBServer.Connection()

                        If Me.ID = 0 Then

                            Me.ID = Cx.Insert(Of T)(pRecord)

                            If Me.ID <> 0 Then
                                Result = True
                            Else
                                Result = False
                            End If

                        Else
                            Result = Cx.Update(Of T)(pRecord)
                        End If

                    End Using

                Catch ex As Exception
                    Stop
                    Result = False
                    Me.Log.AddEntry(ex.Message)
                End Try
            End If
            Return Result

        End Function

        Public Shared Function Retrieve(Of T As {Class, New})(pID As Integer) As IEntity

            Dim Result As IEntity = Nothing

            Try

                If pID = 0 Then
                    Result = New T
                Else
                    Using Cx = DBServer.Connection

                        Result = Cx.Get(Of T)(pID)

                    End Using
                End If

            Catch ex As Exception
                Result = New T
                Stop
            End Try

            If Result Is Nothing Then
                Result = New T
            End If

            Return Result

        End Function`

**Comment by KarltonKemerait** [comment]
I deleted the original code from the post and instead created a small sample project which demonstrates the issue.

**Comment by KarltonKemerait** [comment]
Anyone reading these?

**Comment by mgravell** [comment]
Yes, multiple people (but mostly: me), however at the current time I have not had an opportunity to investigate this, let alone change anything, so: there was nothing to respond with. Ultimately this isn't my day job, and we don't have a support agreement to answer you in X time, or at all. The code is there if you want to investigate, or it can wait on my availability. Right now, most of my spare time has been going towards the "next steps" for Dapper (see https://github.com/DapperLib/Dapper/issues/1909), although by design that doesn't impact how the existing library behaves.

Short answer, then (too late) "yes, I've seen this; I don't have an answer right now, as I haven't had time to investigate"

**Comment by KarltonKemerait** [comment]
That's quite alright I completely understand and appreciate your effort. I was just wondering because I didn't see any comments. Take your time and don't forget to take a day off now and then!! LOL    Thanks!
