### ISSUE TITLE
Error when running vacuum in sqlite

### ISSUE THREAD

**Issue by kensei** [DapperLib/Dapper#1984]
Hi there,.

When I upgraded dapperlib to 2.1.11, I get an error when I run a vacuum statement.

```
connection.Execute("VACUUM;");
```

```
System.ArgumentException : The CommandType 'StoredProcedure' is not supported. :    at Microsoft.Data.Sqlite.SqliteCommand.set_CommandType(CommandType value)
     at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader) in /_/Dapper/CommandDefinition.cs:line 128
     at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2970
     at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 656
     at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
```

The parser is judging the sql type as StoredProcedure.
How can I fix this?
Thank you in advance.

**Comment by JIIIIL** [comment]
connection.Execute("VACUUM;", commandType: CommandType.Text);

**Comment by mgravell** [comment]
Well damn; single-word statements. That's fun! I'll see if I can change the automatic detection to compensate, thanks. This was due to a change in 2.1.11 to make using stored procedures easier

**Comment by mgravell** [comment]
PR in progress
