### ISSUE TITLE
Problem with DateOnly mapping when updating form v2.1.35 to 2.1.44

### ISSUE THREAD

**Issue by glebron-woffu** [DapperLib/Dapper#2071]
I used to have this custom type handler configured:
`SqlMapper.AddTypeHandler(new DapperSqlDateOnlyTypeHandler());`

Mapping class is:

```
public class DapperSqlDateOnlyTypeHandler : SqlMapper.TypeHandler<DateOnly>
{
    public override void SetValue(IDbDataParameter parameter, DateOnly date)
        => parameter.Value = date.ToDateTime(new TimeOnly(0, 0));

    public override DateOnly Parse(object value)
        => DateOnly.FromDateTime((DateTime)value);
}

```
This was working fine, but looks like the DateOnly support was added in [2.1.37](https://github.com/DapperLib/Dapper/releases/tag/2.1.37) but
Now I am getting this error:
```
System.Data.DataException
Error parsing column 1 (Date=669745 - Int32)
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3948
Inner exception:
InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateOnly'.
```
   Thing is, the Date column is column 1, but somehow is parsing column 0 value
 Query result: 
`   669745	2023-11-01	NULL	NULL	...`

So I am a bit confused, in v2.1.35 I didn't have this problem. I removed custom mapper SqlMapper.AddTypeHandler(new DapperSqlDateOnlyTypeHandler()); and still same problem.
Edit:
In another query, I set date only field as first one:
`2023-11-01	0 	0`
The error is:
```
System.Data.DataException
Error parsing column 0 (Date=n/a - Unable to cast object of type 'System.DateTime' to type 'System.DateOnly'.)
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3948
   at Deserialize68929759-6271-4665-a68e-ff25a40601eb(DbDataReader)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command)
```
The class is:
```

public record TestClass
{
    public DateOnly Date { get; set; }
    public int First { get; set; }
    public int Second { get; set; }
}

```

**Comment by mkorsukov** [comment]
@GonzaloVisma Do you use the `System.Data.SqlClient` or `Microsoft.Data.SqlClient` in a combination with Dapper? I have been using the first one with the same workaround you listed above. But recently I have switched to `Microsoft.Data.SqlClient` and workaroud is not required any more.

**Comment by mkorsukov** [comment]
@GonzaloVisma Here is my current setup for data-related project:
```xml
<ItemGroup>
  <PackageReference Include="Dapper" Version="2.1.37" />
  <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
</ItemGroup>
```

**Comment by mgravell** [comment]
I have been unable to get a repro of this failing; for now I guess I have no choice except to revert that change, but if anyone who was seeing this problem could show a runnable repro against 2.1.44 (or similar affected), I'd be very grateful

**Comment by akurone** [comment]
> I have been unable to get a repro of this failing; for now I guess I have no choice except to revert that change, but if anyone who was seeing this problem could show a runnable repro against 2.1.44 (or similar affected), I'd be very grateful

hello marc,

i am experiencing the same issue; i could not produce a runnable repro; but i tried to pin point it; afaik, there is no direct cast from `DateTime` to `DateOnly`:
![image](https://github.com/DapperLib/Dapper/assets/841676/b71e5acc-686f-4b06-908d-0d2fb1be1a2d)

MSSQL might have a suitable data type that can be casted as `DateOnly` but i am working with ORACLE and this is not the case here.

i had a custom converter for `DateOnly` which worked fine before 2.1.44:
![image](https://github.com/DapperLib/Dapper/assets/841676/5cc30d2e-d60f-42f3-84e9-7c22fa258770)

with 2.1.44 my custom converter never gets invoked and i get the cast error.

btw, i expected custom converter to take precedence but that did not work as i expected; so i reverted back to 2.1.35

hope this helps.

**Comment by ThomasHeijtink** [comment]
Is there already an update on this issue?

**Comment by GonzaloVisma** [comment]
> Is there already an update on this issue?

I'm affraid there is no news...
I am still using the customs handlers 
`public class DapperSqlDateOnlyTypeHandler : SqlMapper.TypeHandler<DateOnly>
{
    public override void SetValue(IDbDataParameter parameter, DateOnly date)
        => parameter.Value = date.ToDateTime(new TimeOnly(0, 0));

    public override DateOnly Parse(object value)
        => DateOnly.FromDateTime((DateTime)value);
}

public class DapperSqlTimeOnlyTypeHandler : SqlMapper.TypeHandler<TimeOnly>
{
    public override void SetValue(IDbDataParameter parameter, TimeOnly time)
    {
        parameter.Value = time.ToString();
    }

    public override TimeOnly Parse(object value) => TimeOnly.FromTimeSpan((TimeSpan)value);
}`

And registering them in program.cs
`
SqlMapper.AddTypeHandler(new DapperSqlDateOnlyTypeHandler());
SqlMapper.AddTypeHandler(new DapperSqlTimeOnlyTypeHandler());
`

**Comment by DottorPagliaccius** [comment]
I managed to make it work with 2.44.

```csharp
SqlMapper.RemoveTypeMap(typeof(DateOnly));
SqlMapper.RemoveTypeMap(typeof(DateOnly?));
SqlMapper.RemoveTypeMap(typeof(TimeOnly));
SqlMapper.RemoveTypeMap(typeof(TimeOnly?));

SqlMapper.AddTypeHandler(typeof(DateOnly?), new DateOnlyTypeHandler());
SqlMapper.AddTypeHandler(typeof(TimeOnly?), new TimeOnlyTypeHandler());
```

For years we've been stuck with this ugly workaround in every project. Why can't we just fix it?

**Comment by DottorPagliaccius** [comment]
I'm sorry, I didn't mean to be rude. I appreciate the work you and your team do, and I didn't mean to belittle it—please disregard my last sentence. 

(By the way, I use a private corporate feed over which I have no control, and the latest version available is 2.1.44. I'll see about notifying my boss to remove it. Thank you, and sorry again)

**Comment by RobK410** [comment]
I would like to add my 2cents, .44 worked for me. Reverting in .66 broke my code. So now I'm in .44 limbo. I am using Microsoft.Data.SqlClient. I would suggest others update their client with new DateOnly support vs reverting back to no support.

**Comment by mgravell** [comment]
I will try to review what went wrong here and get us back into a working state.

**Comment by mkorsukov** [comment]
I'm on Dapper `2.1.44` and Microsoft.Data.SqlClient `6.0.1` and everything works fine. Upgrading Dapper to `2.1.66` breaks DateOnly/TimeOnly support.

**Comment by Micha-kun** [comment]
Not only with SqlClient, with MySqlConnector 2.4.0 too. Dapper 2.1.44 gives error, but 2.1.44 doesn't.

**Comment by victorprocure** [comment]
Any update on this? Just ran into it after upgrading from 2.1.44 to 2.1.66. Unfortunately can't downgrade as previous version is not listed, is there any work arounds?

**Comment by mgravell** [comment]
2.1.44 is still there; you can simply use 2.1.44 in your csproj and everything will continue to work. I've been on vacation while all this has kicked off - will be looking when I am available.

**Comment by aki-seppanen** [comment]
We had issues on Npgsql with DateOnly/TimeOnly not working on .66, while .44 seems to work fine.

**Comment by ielcoro** [comment]
Me too having issues with DateOnly/TimeOnly on DuckDB, falling back to .44 solves the problem for the time being

**Comment by gabrielsoldani** [comment]
It looks like Npgsql 10.0 [now returns `DateOnly` instead of `DateTime` for `date` columns by default](https://www.npgsql.org/doc/release-notes/10.0.html#date-and-time-are-now-mapped-to-dateonly-and-timeonly) causing problems with Dapper 2.1.66. I haven't tested yet if reverting back to 2.1.44 fixes it.
